### ISSUE TITLE
SIGSEGV with Aeotec MultiSensor 6

### ISSUE THREAD

**Issue by boolangery** [OpenZWave/open-zwave-control-panel#75]
Hi,
When trying to include the MultiSensor 6 in my network, my app just got a SIGSEGV sometimes:

```
2019/10/17 11:36:14 received notification: <ValueRemoved, HomeID: 0xc4398172, NodeID: 8, ValueID: { (Short):  [0 -> 0], genre: System}>
2019/10/17 11:36:14 received notification: <ValueRemoved, HomeID: 0xc4398172, NodeID: 8, ValueID: { (Button):  [0 -> 0], genre: System}>
2019/10/17 11:36:14 received notification: <ValueRemoved, HomeID: 0xc4398172, NodeID: 8, ValueID: { (Button):  [0 -> 0], genre: System}>
2019/10/17 11:36:14 received notification: <ValueRemoved, HomeID: 0xc4398172, NodeID: 8, ValueID: { (List):  [0 -> 0], genre: System}>
2019/10/17 11:36:14 received notification: <ValueRemoved, HomeID: 0xc4398172, NodeID: 8, ValueID: { (Short):  [0 -> 0], genre: System}>
2019/10/17 11:36:14 received notification: <NodeRemoved, HomeID: 0xc4398172, NodeID: 8>
2019/10/17 11:36:14 received notification: <ControllerCommand, HomeID: 0xc4398172, NodeID: 8, Event: 7, Notification: MsgComplete>

Thread 11 "OZW-driver" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd37fe700 (LWP 17773)]
tcache_get (tc_idx=1) at malloc.c:2943
2943	malloc.c: No such file or directory.
(gdb) bt
#0  tcache_get (tc_idx=1) at malloc.c:2943
#1  __GI___libc_malloc (bytes=32) at malloc.c:3050
#2  0x00007ffff7503258 in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff7b0c64d in OpenZWave::Internal::Platform::WaitImpl::AddWatcher(void (*)(void*), void*) ()
   from /usr/local/lib64/libopenzwave.so.1.6
#4  0x00007ffff7b0179a in OpenZWave::Internal::Platform::Wait::Multiple(OpenZWave::Internal::Platform::Wait**, unsigned int, int) ()
   from /usr/local/lib64/libopenzwave.so.1.6
#5  0x00007ffff7b6f3df in OpenZWave::Driver::DriverThreadProc(OpenZWave::Internal::Platform::Event*) ()
   from /usr/local/lib64/libopenzwave.so.1.6
#6  0x00007ffff7b0cb53 in OpenZWave::Internal::Platform::ThreadImpl::Run() () from /usr/local/lib64/libopenzwave.so.1.6
#7  0x00007ffff7b0cb69 in OpenZWave::Internal::Platform::ThreadImpl::ThreadProc(void*) () from /usr/local/lib64/libopenzwave.so.1.6
#8  0x00007ffff78006db in start_thread (arg=0x7fffd37fe700) at pthread_create.c:463
#9  0x00007ffff6f8888f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

My app is basically the MinOzw example with some modifications.

**Comment by petergebruers** [comment]
Hi! You posted this issue in OpenZWave/open-zwave-control-panel but you say you run a modified version of MinOZW, is that correct? Does ozwcp crash as well?

I am not aware of such crashes of the library in this specific case but you say you have a "MinOzw example with some modifications." so I'd say, if you zip and drag and drop your test code here I might be able to reproduce your issue.

**Comment by petergebruers** [comment]
BTW I am asking if MinOZW crashes because then I could/should transfer this issue from the ozwcp repo to the OpenZWave repo.

**Comment by boolangery** [comment]
Hey, sorry wrong repo ^^ I did not see I was in ozwcp ! I'll just close the issue here. Thanks !

**Comment by petergebruers** [comment]
You don't need to close it. I can reopen and move to the correct repo...
